name: Deploy Shiny App

on:
  push:
    branches:
      - main  # or your chosen deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'  # Specify your R version

     - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "rcmdcheck", "shiny", "bslib", "ggplot2", "DT", "rsconnect"))'
          Rscript -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")'
          Rscript -e 'renv::restore()'
      - name: Install rsconnect
          run: Rscript -e 'install.packages("rsconnect")'


      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='amclouds', token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
          Rscript -e "rsconnect::deployApp()"
