name: deploy-shiny

on: [push]

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.DEPLOY_SECRET }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          sudo apt-get install -y libmongoc-dev libbson-dev

      - name: Install R dependencies
        run: |
          install.packages(c("Matrix","shiny","bslib","rsconnect","ggplot2","DT","bsicons","reshape2", "htmltools"
            ), dependencies = TRUE, repos = 'http://cran.rstudio.com/')
        shell: Rscript {0}

      - name: Deploy to shinyapps.io
        run: |
          rsconnect::setAccountInfo(
            name='amclouds',
            token='${{ secrets.SHINYAPPS_TOKEN }}',
            secret='${{ secrets.SHINYAPPS_SECRET }}'
          )
          rsconnect::deployApp(
            appName = 'Girls-and-Boys-Birth-Analysis',
            account = 'amclouds',
            server = 'shinyapps.io',
            forceUpdate = TRUE
          )
        shell: Rscript {0}
